[tool.poetry]
name = "somaticseq"
version = "0.0.dev"
description = "SomaticSeq Poetry Venv"
authors = ["Li Tai Fang <ltfang@gmail.com>"]
readme = "README.md"
packages = [{include = "somaticseq"}]


[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pysam = ">=0.21"
numpy = "^2.0"
scipy = "^1.10"
pandas = "^2.0"
xgboost = "^2.0"
pydantic = "^2.0"
ipykernel = "^6.20"

[build-system]
requires = ["poetry-core"]
